///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SuraClaims.Motor
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AgregarDatosLesionesTercerosUBER recording.
    /// </summary>
    [TestModule("45a1f435-7339-4d2f-9d20-6f28177bba84", ModuleType.Recording, 1)]
    public partial class AgregarDatosLesionesTercerosUBER : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::SuraClaims.SuraClaimsRepository repository.
        /// </summary>
        public static global::SuraClaims.SuraClaimsRepository repo = global::SuraClaims.SuraClaimsRepository.Instance;

        static AgregarDatosLesionesTercerosUBER instance = new AgregarDatosLesionesTercerosUBER();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AgregarDatosLesionesTercerosUBER()
        {
            ANIO = "2019";
            Marca = "CHEVROLET";
            Modelo = "ONIX";
            Tipo = "AUTO";
            Patente = "jio098";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AgregarDatosLesionesTercerosUBER Instance
        {
            get { return instance; }
        }

#region Variables

        string _Marca;

        /// <summary>
        /// Gets or sets the value of variable Marca.
        /// </summary>
        [TestVariable("a193a25c-7100-409f-9566-990c0882e7ff")]
        public string Marca
        {
            get { return _Marca; }
            set { _Marca = value; }
        }

        string _Modelo;

        /// <summary>
        /// Gets or sets the value of variable Modelo.
        /// </summary>
        [TestVariable("95b5abd3-ba58-4e0e-8094-a74d7c89cba2")]
        public string Modelo
        {
            get { return _Modelo; }
            set { _Modelo = value; }
        }

        string _Tipo;

        /// <summary>
        /// Gets or sets the value of variable Tipo.
        /// </summary>
        [TestVariable("aac4fca9-a557-4252-a941-55dcfaa4b89d")]
        public string Tipo
        {
            get { return _Tipo; }
            set { _Tipo = value; }
        }

        string _Patente;

        /// <summary>
        /// Gets or sets the value of variable Patente.
        /// </summary>
        [TestVariable("3968f3fd-57c0-4026-91d2-49fc6599efbe")]
        public string Patente
        {
            get { return _Patente; }
            set { _Patente = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("e7903828-6ac1-46d3-a887-f52fdafb621a")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Responsabilidad.
        /// </summary>
        [TestVariable("811dedf4-3591-4699-a423-2ca44a8785f1")]
        public string Responsabilidad
        {
            get { return repo.Responsabilidad; }
            set { repo.Responsabilidad = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable ANIO.
        /// </summary>
        [TestVariable("12c92045-b539-43af-b6b1-20b4a6c6b89c")]
        public string ANIO
        {
            get { return repo.Anio; }
            set { repo.Anio = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.btn_agregarDanoYLesionesTerceros' at Center.", repo.SuraClaims.Motor.btn_agregarDanoYLesionesTercerosInfo, new RecordItemIndex(0));
            repo.SuraClaims.Motor.btn_agregarDanoYLesionesTerceros.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to exist. Associated repository item: 'SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoDeTercero'", repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoDeTerceroInfo, new ActionTimeout(10000), new RecordItemIndex(1));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoDeTerceroInfo.WaitForExists(10000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.bttn_AgregarConductorUber' at Center.", repo.SuraClaims.Motor.InformacionSiniestro.bttn_AgregarConductorUberInfo, new RecordItemIndex(2));
            repo.SuraClaims.Motor.InformacionSiniestro.bttn_AgregarConductorUber.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SuraClaims.Motor.txt_DetalleDeLosLesionados'", repo.SuraClaims.Motor.txt_DetalleDeLosLesionadosInfo, new ActionTimeout(30000), new RecordItemIndex(3));
            repo.SuraClaims.Motor.txt_DetalleDeLosLesionadosInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.bttn_Agregar' at Center.", repo.SuraClaims.Motor.InformacionSiniestro.bttn_AgregarInfo, new RecordItemIndex(4));
            repo.SuraClaims.Motor.InformacionSiniestro.bttn_Agregar.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.txt_DetalleDeLosLesionados' at 154;8.", repo.SuraClaims.Motor.txt_DetalleDeLosLesionadosInfo, new RecordItemIndex(5));
            repo.SuraClaims.Motor.txt_DetalleDeLosLesionados.Click("154;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.txt_TipoDocumento_MotorUber' at 74;12.", repo.SuraClaims.Motor.InformacionSiniestro.txt_TipoDocumento_MotorUberInfo, new RecordItemIndex(6));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_TipoDocumento_MotorUber.Click("74;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.option_DNI' at 29;9.", repo.SuraClaims.Motor.option_DNIInfo, new RecordItemIndex(7));
            repo.SuraClaims.Motor.option_DNI.Click("29;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'SuraClaims.Motor.Copy_of_option_DNI'", repo.SuraClaims.Motor.Copy_of_option_DNIInfo, new ActionTimeout(30000), new RecordItemIndex(8));
            repo.SuraClaims.Motor.Copy_of_option_DNIInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(9));
            Delay.Duration(3000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.txt_DetalleDeLosLesionados' at 154;8.", repo.SuraClaims.Motor.txt_DetalleDeLosLesionadosInfo, new RecordItemIndex(10));
            //repo.SuraClaims.Motor.txt_DetalleDeLosLesionados.Click("154;8");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.txt_Nro_Documento_Motor_Uber' at Center.", repo.SuraClaims.Motor.InformacionSiniestro.txt_Nro_Documento_Motor_UberInfo, new RecordItemIndex(11));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_Nro_Documento_Motor_Uber.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}' with focus on 'SuraClaims.Motor.InformacionSiniestro.txt_Nro_Documento_Motor_Uber'.", repo.SuraClaims.Motor.InformacionSiniestro.txt_Nro_Documento_Motor_UberInfo, new RecordItemIndex(12));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_Nro_Documento_Motor_Uber.PressKeys("{LControlKey down}{Akey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '25667887' with focus on 'SuraClaims.Motor.InformacionSiniestro.txt_Nro_Documento_Motor_Uber'.", repo.SuraClaims.Motor.InformacionSiniestro.txt_Nro_Documento_Motor_UberInfo, new RecordItemIndex(13));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_Nro_Documento_Motor_Uber.EnsureVisible();
            Keyboard.Press("25667887");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.txtbox_Nombre' at 46;13.", repo.SuraClaims.Motor.txtbox_NombreInfo, new RecordItemIndex(14));
            repo.SuraClaims.Motor.txtbox_Nombre.Click("46;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'PRUEBA' with focus on 'SuraClaims.Motor.txtbox_Nombre'.", repo.SuraClaims.Motor.txtbox_NombreInfo, new RecordItemIndex(15));
            repo.SuraClaims.Motor.txtbox_Nombre.PressKeys("PRUEBA");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.txtbox_Apellido' at 35;9.", repo.SuraClaims.Motor.txtbox_ApellidoInfo, new RecordItemIndex(16));
            repo.SuraClaims.Motor.txtbox_Apellido.Click("35;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'DOS' with focus on 'SuraClaims.Motor.txtbox_Apellido'.", repo.SuraClaims.Motor.txtbox_ApellidoInfo, new RecordItemIndex(17));
            repo.SuraClaims.Motor.txtbox_Apellido.PressKeys("DOS");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.txt_DetalleDeLosLesionados' at 154;8.", repo.SuraClaims.Motor.txt_DetalleDeLosLesionadosInfo, new RecordItemIndex(18));
            repo.SuraClaims.Motor.txt_DetalleDeLosLesionados.Click("154;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.btn_Aceptar' at 27;11.", repo.SuraClaims.Motor.btn_AceptarInfo, new RecordItemIndex(19));
            repo.SuraClaims.Motor.btn_Aceptar.Click("27;11");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.op_ambulancia' at 8;7.", repo.SuraClaims.Motor.op_ambulanciaInfo, new RecordItemIndex(20));
            //repo.SuraClaims.Motor.op_ambulancia.Click("8;7");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.btn_Danios_No' at 6;8.", repo.SuraClaims.Motor.btn_Danios_NoInfo, new RecordItemIndex(21));
            //repo.SuraClaims.Motor.btn_Danios_No.Click("6;8");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.op_responsabilidad' at 6;6.", repo.SuraClaims.Motor.op_responsabilidadInfo, new RecordItemIndex(22));
            //repo.SuraClaims.Motor.op_responsabilidad.Click("6;6");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.txtAnio' at 7;4.", repo.SuraClaims.Motor.InformacionSiniestro.txtAnioInfo, new RecordItemIndex(23));
            repo.SuraClaims.Motor.InformacionSiniestro.txtAnio.Click("7;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}' with focus on 'SuraClaims.Motor.InformacionSiniestro.txtAnio'.", repo.SuraClaims.Motor.InformacionSiniestro.txtAnioInfo, new RecordItemIndex(24));
            repo.SuraClaims.Motor.InformacionSiniestro.txtAnio.PressKeys("{LControlKey down}{Akey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ANIO' with focus on 'SuraClaims.Motor.InformacionSiniestro.txtAnio'.", repo.SuraClaims.Motor.InformacionSiniestro.txtAnioInfo, new RecordItemIndex(25));
            repo.SuraClaims.Motor.InformacionSiniestro.txtAnio.EnsureVisible();
            Keyboard.Press(ANIO);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.lbl_ElementosBasicosDelVehiculo' at Center.", repo.SuraClaims.Motor.InformacionSiniestro.lbl_ElementosBasicosDelVehiculoInfo, new RecordItemIndex(26));
            repo.SuraClaims.Motor.InformacionSiniestro.lbl_ElementosBasicosDelVehiculo.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.txt_Marca' at 34;9.", repo.SuraClaims.Motor.txt_MarcaInfo, new RecordItemIndex(27));
            repo.SuraClaims.Motor.txt_Marca.Click("34;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}' with focus on 'SuraClaims.Motor.txt_Marca'.", repo.SuraClaims.Motor.txt_MarcaInfo, new RecordItemIndex(28));
            repo.SuraClaims.Motor.txt_Marca.PressKeys("{LControlKey down}{Akey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Marca' with focus on 'SuraClaims.Motor.txt_Marca'.", repo.SuraClaims.Motor.txt_MarcaInfo, new RecordItemIndex(29));
            repo.SuraClaims.Motor.txt_Marca.PressKeys(Marca);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.lbl_ElementosBasicosDelVehiculo' at Center.", repo.SuraClaims.Motor.InformacionSiniestro.lbl_ElementosBasicosDelVehiculoInfo, new RecordItemIndex(30));
            repo.SuraClaims.Motor.InformacionSiniestro.lbl_ElementosBasicosDelVehiculo.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.textMarca' at 48;10.", repo.SuraClaims.Motor.textMarcaInfo, new RecordItemIndex(31));
            //repo.SuraClaims.Motor.textMarca.Click("48;10");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.txt_Modelo' at 36;12.", repo.SuraClaims.Motor.txt_ModeloInfo, new RecordItemIndex(32));
            repo.SuraClaims.Motor.txt_Modelo.Click("36;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}' with focus on 'SuraClaims.Motor.txt_Modelo'.", repo.SuraClaims.Motor.txt_ModeloInfo, new RecordItemIndex(33));
            repo.SuraClaims.Motor.txt_Modelo.PressKeys("{LControlKey down}{Akey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Modelo' with focus on 'SuraClaims.Motor.txt_Modelo'.", repo.SuraClaims.Motor.txt_ModeloInfo, new RecordItemIndex(34));
            repo.SuraClaims.Motor.txt_Modelo.PressKeys(Modelo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.lbl_ElementosBasicosDelVehiculo' at Center.", repo.SuraClaims.Motor.InformacionSiniestro.lbl_ElementosBasicosDelVehiculoInfo, new RecordItemIndex(35));
            repo.SuraClaims.Motor.InformacionSiniestro.lbl_ElementosBasicosDelVehiculo.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.txtModelo1' at 29;5.", repo.SuraClaims.Motor.txtModelo1Info, new RecordItemIndex(36));
            //repo.SuraClaims.Motor.txtModelo1.Click("29;5");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.SiniestroTercero.txt_TipoVehiculo' at 88;7.", repo.SuraClaims.SiniestroTercero.txt_TipoVehiculoInfo, new RecordItemIndex(37));
            repo.SuraClaims.SiniestroTercero.txt_TipoVehiculo.Click("88;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}' with focus on 'SuraClaims.SiniestroTercero.txt_TipoVehiculo'.", repo.SuraClaims.SiniestroTercero.txt_TipoVehiculoInfo, new RecordItemIndex(38));
            repo.SuraClaims.SiniestroTercero.txt_TipoVehiculo.PressKeys("{LControlKey down}{Akey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Tipo' with focus on 'SuraClaims.SiniestroTercero.txt_TipoVehiculo'.", repo.SuraClaims.SiniestroTercero.txt_TipoVehiculoInfo, new RecordItemIndex(39));
            repo.SuraClaims.SiniestroTercero.txt_TipoVehiculo.PressKeys(Tipo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.lbl_ElementosBasicosDelVehiculo' at Center.", repo.SuraClaims.Motor.InformacionSiniestro.lbl_ElementosBasicosDelVehiculoInfo, new RecordItemIndex(40));
            repo.SuraClaims.Motor.InformacionSiniestro.lbl_ElementosBasicosDelVehiculo.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'SuraClaims.SiniestroTercero.Copy_of_txtTipoVehiculo'", repo.SuraClaims.SiniestroTercero.Copy_of_txtTipoVehiculoInfo, new ActionTimeout(30000), new RecordItemIndex(41));
            repo.SuraClaims.SiniestroTercero.Copy_of_txtTipoVehiculoInfo.WaitForNotExists(30000);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.txtTipo' at 27;7.", repo.SuraClaims.Motor.txtTipoInfo, new RecordItemIndex(42));
            //repo.SuraClaims.Motor.txtTipo.Click("27;7");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.SiniestroTercero.txt_Patente' at 29;8.", repo.SuraClaims.SiniestroTercero.txt_PatenteInfo, new RecordItemIndex(43));
            repo.SuraClaims.SiniestroTercero.txt_Patente.Click("29;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}' with focus on 'SuraClaims.SiniestroTercero.txt_Patente'.", repo.SuraClaims.SiniestroTercero.txt_PatenteInfo, new RecordItemIndex(44));
            repo.SuraClaims.SiniestroTercero.txt_Patente.PressKeys("{LControlKey down}{Akey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Patente' with focus on 'SuraClaims.SiniestroTercero.txt_Patente'.", repo.SuraClaims.SiniestroTercero.txt_PatenteInfo, new RecordItemIndex(45));
            repo.SuraClaims.SiniestroTercero.txt_Patente.PressKeys(Patente);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.btn_Aceptar' at Center.", repo.SuraClaims.Motor.btn_AceptarInfo, new RecordItemIndex(46));
            repo.SuraClaims.Motor.btn_Aceptar.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'SuraClaims.Txt_Validaciones.txt_Paso3'", repo.SuraClaims.Txt_Validaciones.txt_Paso3Info, new ActionTimeout(5000), new RecordItemIndex(47));
            repo.SuraClaims.Txt_Validaciones.txt_Paso3Info.WaitForExists(5000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
