///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SuraClaims.Motor
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DescripTipoSiniestro_Tercero_Colision recording.
    /// </summary>
    [TestModule("61e4dcef-1aae-4a13-840b-3898125ec2e1", ModuleType.Recording, 1)]
    public partial class DescripTipoSiniestro_Tercero_Colision : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::SuraClaims.SuraClaimsRepository repository.
        /// </summary>
        public static global::SuraClaims.SuraClaimsRepository repo = global::SuraClaims.SuraClaimsRepository.Instance;

        static DescripTipoSiniestro_Tercero_Colision instance = new DescripTipoSiniestro_Tercero_Colision();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DescripTipoSiniestro_Tercero_Colision()
        {
            TipoAccidente = "Colisión";
            TipoColision = "Vehículo";
            DanioTercero = "Frontal";
            DescripcionDanios = "Choque Frontal";
            CantPasaj = "1";
            Dolencia = "No";
            CantAsegu = "1";
            Dolencias = "No";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DescripTipoSiniestro_Tercero_Colision Instance
        {
            get { return instance; }
        }

#region Variables

        string _DescripcionDanios;

        /// <summary>
        /// Gets or sets the value of variable DescripcionDanios.
        /// </summary>
        [TestVariable("e9963c27-334f-489a-8169-3eb341beceaa")]
        public string DescripcionDanios
        {
            get { return _DescripcionDanios; }
            set { _DescripcionDanios = value; }
        }

        string _Dolencias;

        /// <summary>
        /// Gets or sets the value of variable Dolencias.
        /// </summary>
        [TestVariable("0f1635ee-f2e4-49d3-a707-bf774fba2dea")]
        public string Dolencias
        {
            get { return _Dolencias; }
            set { _Dolencias = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("e7903828-6ac1-46d3-a887-f52fdafb621a")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable TipoAccidente.
        /// </summary>
        [TestVariable("a1f3e695-bff6-4f81-8ea8-9af16e84c8bb")]
        public string TipoAccidente
        {
            get { return repo.TipoAccidente; }
            set { repo.TipoAccidente = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable TipoColision.
        /// </summary>
        [TestVariable("818e442a-84c8-4b4a-9ca1-923462714ab4")]
        public string TipoColision
        {
            get { return repo.TipoColision; }
            set { repo.TipoColision = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable DanioTercero.
        /// </summary>
        [TestVariable("2ba93c69-e8e8-41c3-95eb-44a7b419c612")]
        public string DanioTercero
        {
            get { return repo.DanioTercero; }
            set { repo.DanioTercero = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Dolencia.
        /// </summary>
        [TestVariable("53daebca-d8bf-414f-b96a-871e390bb227")]
        public string Dolencia
        {
            get { return repo.Dolencia; }
            set { repo.Dolencia = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable CantPasaj.
        /// </summary>
        [TestVariable("e2bf9d33-36d2-4fd9-a145-278adbc85d1a")]
        public string CantPasaj
        {
            get { return repo.CantPasaj; }
            set { repo.CantPasaj = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable CantAsegu.
        /// </summary>
        [TestVariable("0f588447-09db-4a8a-84db-fdd707cbd88e")]
        public string CantAsegu
        {
            get { return repo.CantAsegu; }
            set { repo.CantAsegu = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoDeTercero' at Center.", repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoDeTerceroInfo, new RecordItemIndex(0));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoDeTercero.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SuraClaims.Motor.txt_TipoAccidente' at Center.", repo.SuraClaims.Motor.txt_TipoAccidenteInfo, new RecordItemIndex(1));
            repo.SuraClaims.Motor.txt_TipoAccidente.DoubleClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Colisión' with focus on 'SuraClaims.Motor.txt_TipoAccidente'.", repo.SuraClaims.Motor.txt_TipoAccidenteInfo, new RecordItemIndex(2));
            repo.SuraClaims.Motor.txt_TipoAccidente.PressKeys("Colisión");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.SiniestroTercero.select_TipoAccidente_Colision' at Center.", repo.SuraClaims.Motor.SiniestroTercero.select_TipoAccidente_ColisionInfo, new RecordItemIndex(3));
            repo.SuraClaims.Motor.SiniestroTercero.select_TipoAccidente_Colision.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$TipoAccidente' with focus on 'SuraClaims.Motor.txt_TipoAccidente'.", repo.SuraClaims.Motor.txt_TipoAccidenteInfo, new RecordItemIndex(4));
            //repo.SuraClaims.Motor.txt_TipoAccidente.PressKeys(TipoAccidente);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.SiniestroTercero.select_TipoAccidente' at Center.", repo.SuraClaims.Motor.SiniestroTercero.select_TipoAccidenteInfo, new RecordItemIndex(5));
            //repo.SuraClaims.Motor.SiniestroTercero.select_TipoAccidente.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoDeTercero' at Center.", repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoDeTerceroInfo, new RecordItemIndex(6));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoDeTercero.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SuraClaims.Motor.SiniestroTercero.txt_ColisionCon' at Center.", repo.SuraClaims.Motor.SiniestroTercero.txt_ColisionConInfo, new RecordItemIndex(7));
            repo.SuraClaims.Motor.SiniestroTercero.txt_ColisionCon.DoubleClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$TipoColision' with focus on 'SuraClaims.Motor.SiniestroTercero.txt_ColisionCon'.", repo.SuraClaims.Motor.SiniestroTercero.txt_ColisionConInfo, new RecordItemIndex(8));
            repo.SuraClaims.Motor.SiniestroTercero.txt_ColisionCon.PressKeys(TipoColision);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.SiniestroTercero.SelectTipoColision' at Center.", repo.SuraClaims.Motor.SiniestroTercero.SelectTipoColisionInfo, new RecordItemIndex(9));
            repo.SuraClaims.Motor.SiniestroTercero.SelectTipoColision.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoDeTercero' at Center.", repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoDeTerceroInfo, new RecordItemIndex(10));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoDeTercero.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SuraClaims.Motor.SiniestroTercero.txt_DanioATercero' at Center.", repo.SuraClaims.Motor.SiniestroTercero.txt_DanioATerceroInfo, new RecordItemIndex(11));
            repo.SuraClaims.Motor.SiniestroTercero.txt_DanioATercero.DoubleClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$DanioTercero' with focus on 'SuraClaims.Motor.SiniestroTercero.txt_DanioATercero'.", repo.SuraClaims.Motor.SiniestroTercero.txt_DanioATerceroInfo, new RecordItemIndex(12));
            repo.SuraClaims.Motor.SiniestroTercero.txt_DanioATercero.PressKeys(DanioTercero);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.SiniestroTercero.SelectDanioTerceroFrontal' at Center.", repo.SuraClaims.Motor.SiniestroTercero.SelectDanioTerceroFrontalInfo, new RecordItemIndex(13));
            repo.SuraClaims.Motor.SiniestroTercero.SelectDanioTerceroFrontal.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoDeTercero' at Center.", repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoDeTerceroInfo, new RecordItemIndex(14));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoDeTercero.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SuraClaims.Motor.SiniestroTercero.txt_Dolencias' at Center.", repo.SuraClaims.Motor.SiniestroTercero.txt_DolenciasInfo, new RecordItemIndex(15));
            repo.SuraClaims.Motor.SiniestroTercero.txt_Dolencias.DoubleClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Dolencias' with focus on 'SuraClaims.Motor.SiniestroTercero.txt_Dolencias'.", repo.SuraClaims.Motor.SiniestroTercero.txt_DolenciasInfo, new RecordItemIndex(16));
            repo.SuraClaims.Motor.SiniestroTercero.txt_Dolencias.PressKeys(Dolencias);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.SiniestroTercero.SelectDolencia' at Center.", repo.SuraClaims.Motor.SiniestroTercero.SelectDolenciaInfo, new RecordItemIndex(17));
            repo.SuraClaims.Motor.SiniestroTercero.SelectDolencia.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoDeTercero' at Center.", repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoDeTerceroInfo, new RecordItemIndex(18));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoDeTercero.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SuraClaims.Motor.SiniestroTercero.txt_CantPasajTerc' at Center.", repo.SuraClaims.Motor.SiniestroTercero.txt_CantPasajTercInfo, new RecordItemIndex(19));
            repo.SuraClaims.Motor.SiniestroTercero.txt_CantPasajTerc.DoubleClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CantPasaj' with focus on 'SuraClaims.Motor.SiniestroTercero.txt_CantPasajTerc'.", repo.SuraClaims.Motor.SiniestroTercero.txt_CantPasajTercInfo, new RecordItemIndex(20));
            repo.SuraClaims.Motor.SiniestroTercero.txt_CantPasajTerc.PressKeys(CantPasaj);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.SiniestroTercero.SelectCantPasajTerc' at Center.", repo.SuraClaims.Motor.SiniestroTercero.SelectCantPasajTercInfo, new RecordItemIndex(21));
            repo.SuraClaims.Motor.SiniestroTercero.SelectCantPasajTerc.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SuraClaims.Motor.SiniestroTercero.txt_CantAseg' at Center.", repo.SuraClaims.Motor.SiniestroTercero.txt_CantAsegInfo, new RecordItemIndex(22));
            repo.SuraClaims.Motor.SiniestroTercero.txt_CantAseg.DoubleClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CantAsegu' with focus on 'SuraClaims.Motor.SiniestroTercero.txt_CantAseg'.", repo.SuraClaims.Motor.SiniestroTercero.txt_CantAsegInfo, new RecordItemIndex(23));
            repo.SuraClaims.Motor.SiniestroTercero.txt_CantAseg.PressKeys(CantAsegu);
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.SiniestroTercero.SelectCantAseg' at Center.", repo.SuraClaims.Motor.SiniestroTercero.SelectCantAsegInfo, new RecordItemIndex(24));
            repo.SuraClaims.Motor.SiniestroTercero.SelectCantAseg.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoDeTercero' at Center.", repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoDeTerceroInfo, new RecordItemIndex(25));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoDeTercero.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SuraClaims.Motor.SiniestroTercero.txt_DescripDaniosTercero' at Center.", repo.SuraClaims.Motor.SiniestroTercero.txt_DescripDaniosTerceroInfo, new RecordItemIndex(26));
            repo.SuraClaims.Motor.SiniestroTercero.txt_DescripDaniosTercero.DoubleClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$DescripcionDanios' with focus on 'SuraClaims.Motor.SiniestroTercero.txt_DescripDaniosTercero'.", repo.SuraClaims.Motor.SiniestroTercero.txt_DescripDaniosTerceroInfo, new RecordItemIndex(27));
            repo.SuraClaims.Motor.SiniestroTercero.txt_DescripDaniosTercero.PressKeys(DescripcionDanios);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoDeTercero' at Center.", repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoDeTerceroInfo, new RecordItemIndex(28));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoDeTercero.Click();
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.SuraClaims.Self, false, new RecordItemIndex(29));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.btn_Aceptar' at Center.", repo.SuraClaims.Motor.btn_AceptarInfo, new RecordItemIndex(30));
            repo.SuraClaims.Motor.btn_Aceptar.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SuraClaims.Txt_Validaciones.txt_Paso3'", repo.SuraClaims.Txt_Validaciones.txt_Paso3Info, new ActionTimeout(30000), new RecordItemIndex(31));
            repo.SuraClaims.Txt_Validaciones.txt_Paso3Info.WaitForExists(30000);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.SuraClaims.Self, false, new RecordItemIndex(32));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.bttn_Finalizar' at Center.", repo.SuraClaims.Motor.InformacionSiniestro.bttn_FinalizarInfo, new RecordItemIndex(33));
            repo.SuraClaims.Motor.InformacionSiniestro.bttn_Finalizar.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
