///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SuraClaims.Inspecciones
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CrearServicio_DatosProveedor recording.
    /// </summary>
    [TestModule("ff0ac553-73c8-480b-8b2e-29eb6fe4b36f", ModuleType.Recording, 1)]
    public partial class CrearServicio_DatosProveedor : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::SuraClaims.SuraClaimsRepository repository.
        /// </summary>
        public static global::SuraClaims.SuraClaimsRepository repo = global::SuraClaims.SuraClaimsRepository.Instance;

        static CrearServicio_DatosProveedor instance = new CrearServicio_DatosProveedor();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CrearServicio_DatosProveedor()
        {
            FechaFinalizacionServicio = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CrearServicio_DatosProveedor Instance
        {
            get { return instance; }
        }

#region Variables

        string _FechaFinalizacionServicio;

        /// <summary>
        /// Gets or sets the value of variable FechaFinalizacionServicio.
        /// </summary>
        [TestVariable("25f7f35a-f09e-4330-a4ef-c36036742877")]
        public string FechaFinalizacionServicio
        {
            get { return _FechaFinalizacionServicio; }
            set { _FechaFinalizacionServicio = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("e7903828-6ac1-46d3-a887-f52fdafb621a")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'SuraClaims.Inspeccion.txt_FechaFinalizacionServicio' and assigning its value to variable 'FechaFinalizacionServicio'.", repo.SuraClaims.Inspeccion.txt_FechaFinalizacionServicioInfo, new RecordItemIndex(0));
            FechaFinalizacionServicio = repo.SuraClaims.Inspeccion.txt_FechaFinalizacionServicio.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$FechaFinalizacionServicio' with focus on 'SuraClaims.Inspeccion.input_FechaInspeccionOrion'.", repo.SuraClaims.Inspeccion.input_FechaInspeccionOrionInfo, new RecordItemIndex(1));
            repo.SuraClaims.Inspeccion.input_FechaInspeccionOrion.PressKeys(FechaFinalizacionServicio);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Inspeccion.txt_InstruccionesparaProveedor' at Center.", repo.SuraClaims.Inspeccion.txt_InstruccionesparaProveedorInfo, new RecordItemIndex(2));
            repo.SuraClaims.Inspeccion.txt_InstruccionesparaProveedor.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 15s to not exist. Associated repository item: 'SuraClaims.Inspeccion.Copy_of_input_FechaInspeccionOrion'", repo.SuraClaims.Inspeccion.Copy_of_input_FechaInspeccionOrionInfo, new ActionTimeout(15000), new RecordItemIndex(3));
            repo.SuraClaims.Inspeccion.Copy_of_input_FechaInspeccionOrionInfo.WaitForNotExists(15000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Inspeccion.input_NombreProveedor' at Center.", repo.SuraClaims.Inspeccion.input_NombreProveedorInfo, new RecordItemIndex(4));
            repo.SuraClaims.Inspeccion.input_NombreProveedor.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(5));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Inspeccion.option_Proveedor' at Center.", repo.SuraClaims.Inspeccion.option_ProveedorInfo, new RecordItemIndex(6));
            repo.SuraClaims.Inspeccion.option_Proveedor.Click();
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.SuraClaims.Self, false, new RecordItemIndex(7));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(8));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Inspeccion.bttn_Guardar' at Center.", repo.SuraClaims.Inspeccion.bttn_GuardarInfo, new RecordItemIndex(9));
            repo.SuraClaims.Inspeccion.bttn_Guardar.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SuraClaims.Inspeccion.txt_Servicios'", repo.SuraClaims.Inspeccion.txt_ServiciosInfo, new ActionTimeout(30000), new RecordItemIndex(10));
            repo.SuraClaims.Inspeccion.txt_ServiciosInfo.WaitForExists(30000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
