///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SuraClaims.PlanDeTrabajo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The PreguntasPendientes_Motor recording.
    /// </summary>
    [TestModule("06e3a70d-d41d-4f13-ada3-4e04b24e4638", ModuleType.Recording, 1)]
    public partial class PreguntasPendientes_Motor : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::SuraClaims.SuraClaimsRepository repository.
        /// </summary>
        public static global::SuraClaims.SuraClaimsRepository repo = global::SuraClaims.SuraClaimsRepository.Instance;

        static PreguntasPendientes_Motor instance = new PreguntasPendientes_Motor();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public PreguntasPendientes_Motor()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static PreguntasPendientes_Motor Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("e7903828-6ac1-46d3-a887-f52fdafb621a")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.PlanDeTrabajo.Preguntas.pregunta_AntecedentesSiniestrales' at Center.", repo.SuraClaims.PlanDeTrabajo.Preguntas.pregunta_AntecedentesSiniestralesInfo, new RecordItemIndex(0));
            repo.SuraClaims.PlanDeTrabajo.Preguntas.pregunta_AntecedentesSiniestrales.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.PlanDeTrabajo.option_No' at Center.", repo.SuraClaims.PlanDeTrabajo.option_NoInfo, new RecordItemIndex(1));
            repo.SuraClaims.PlanDeTrabajo.option_No.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.PlanDeTrabajo.Preguntas.pregunta_AntecedentesFraude' at Center.", repo.SuraClaims.PlanDeTrabajo.Preguntas.pregunta_AntecedentesFraudeInfo, new RecordItemIndex(2));
            repo.SuraClaims.PlanDeTrabajo.Preguntas.pregunta_AntecedentesFraude.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.PlanDeTrabajo.option_No' at Center.", repo.SuraClaims.PlanDeTrabajo.option_NoInfo, new RecordItemIndex(3));
            repo.SuraClaims.PlanDeTrabajo.option_No.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
