///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SuraClaims.Actividad
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TerminarCompletarChecklistFraude recording.
    /// </summary>
    [TestModule("7e920630-b616-4433-bae9-eca753cf4765", ModuleType.Recording, 1)]
    public partial class TerminarCompletarChecklistFraude : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::SuraClaims.SuraClaimsRepository repository.
        /// </summary>
        public static global::SuraClaims.SuraClaimsRepository repo = global::SuraClaims.SuraClaimsRepository.Instance;

        static TerminarCompletarChecklistFraude instance = new TerminarCompletarChecklistFraude();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TerminarCompletarChecklistFraude()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TerminarCompletarChecklistFraude Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("e7903828-6ac1-46d3-a887-f52fdafb621a")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Actividad.bttn_Actualizar' at Center.", repo.SuraClaims.Actividad.bttn_ActualizarInfo, new RecordItemIndex(0));
            repo.SuraClaims.Actividad.bttn_Actualizar.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 20s to not exist. Associated repository item: 'SuraClaims.Actividad.ventana_PreguntasPendientes'", repo.SuraClaims.Actividad.ventana_PreguntasPendientesInfo, new ActionTimeout(20000), new RecordItemIndex(1));
            repo.SuraClaims.Actividad.ventana_PreguntasPendientesInfo.WaitForNotExists(20000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Actividad.bttn_Completar' at Center.", repo.SuraClaims.Actividad.bttn_CompletarInfo, new RecordItemIndex(2));
            repo.SuraClaims.Actividad.bttn_Completar.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 20s to not exist. Associated repository item: 'SuraClaims.Actividad.a_CompletarChecklistFraude'", repo.SuraClaims.Actividad.a_CompletarChecklistFraudeInfo, new ActionTimeout(20000), new RecordItemIndex(3));
            repo.SuraClaims.Actividad.a_CompletarChecklistFraudeInfo.WaitForNotExists(20000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
