///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SuraClaims.Reclamos
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Completar_Checklist recording.
    /// </summary>
    [TestModule("a995836d-55a4-4293-bfd7-2b567fe13d8d", ModuleType.Recording, 1)]
    public partial class Completar_Checklist : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::SuraClaims.SuraClaimsRepository repository.
        /// </summary>
        public static global::SuraClaims.SuraClaimsRepository repo = global::SuraClaims.SuraClaimsRepository.Instance;

        static Completar_Checklist instance = new Completar_Checklist();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Completar_Checklist()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Completar_Checklist Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("e7903828-6ac1-46d3-a887-f52fdafb621a")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SuraClaims.Reclamos.input_Vehiculo'", repo.SuraClaims.Reclamos.input_VehiculoInfo, new ActionTimeout(30000), new RecordItemIndex(0));
            repo.SuraClaims.Reclamos.input_VehiculoInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Reclamos.arrow_Vehiculo' at Center.", repo.SuraClaims.Reclamos.arrow_VehiculoInfo, new RecordItemIndex(1));
            repo.SuraClaims.Reclamos.arrow_Vehiculo.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Reclamos.option_EditarDetalles' at Center.", repo.SuraClaims.Reclamos.option_EditarDetallesInfo, new RecordItemIndex(2));
            repo.SuraClaims.Reclamos.option_EditarDetalles.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SuraClaims.Reclamos.input_Incidente'", repo.SuraClaims.Reclamos.input_IncidenteInfo, new ActionTimeout(30000), new RecordItemIndex(3));
            repo.SuraClaims.Reclamos.input_IncidenteInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Reclamos.lbl_IndicadorFraude' at Center.", repo.SuraClaims.Reclamos.lbl_IndicadorFraudeInfo, new RecordItemIndex(4));
            repo.SuraClaims.Reclamos.lbl_IndicadorFraude.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SuraClaims.Reclamos.txt_VehiculoInvolucrado'", repo.SuraClaims.Reclamos.txt_VehiculoInvolucradoInfo, new ActionTimeout(30000), new RecordItemIndex(5));
            repo.SuraClaims.Reclamos.txt_VehiculoInvolucradoInfo.WaitForExists(30000);
            
            // Completo opciones
            Report.Log(ReportLevel.Info, "Section", "Completo opciones", new RecordItemIndex(6));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Reclamos.rdb_AntecedentesSiniestrales1' at Center.", repo.SuraClaims.Reclamos.rdb_AntecedentesSiniestrales1Info, new RecordItemIndex(7));
            repo.SuraClaims.Reclamos.rdb_AntecedentesSiniestrales1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Reclamos.rdb_AntecedentesFraude1' at Center.", repo.SuraClaims.Reclamos.rdb_AntecedentesFraude1Info, new RecordItemIndex(8));
            repo.SuraClaims.Reclamos.rdb_AntecedentesFraude1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Reclamos.rdb_AntecedentesSiniestrales2' at Center.", repo.SuraClaims.Reclamos.rdb_AntecedentesSiniestrales2Info, new RecordItemIndex(9));
            repo.SuraClaims.Reclamos.rdb_AntecedentesSiniestrales2.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Reclamos.bttn_Aceptar' at Center.", repo.SuraClaims.Reclamos.bttn_AceptarInfo, new RecordItemIndex(10));
            repo.SuraClaims.Reclamos.bttn_Aceptar.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Reclamos.rdb_AntecedentesFraude2' at Center.", repo.SuraClaims.Reclamos.rdb_AntecedentesFraude2Info, new RecordItemIndex(11));
            repo.SuraClaims.Reclamos.rdb_AntecedentesFraude2.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
