///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SuraClaims.JuiciosyMediaciones
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The NuevoLitigio recording.
    /// </summary>
    [TestModule("a19f4e8c-aea5-4960-b548-5a21f3380e8c", ModuleType.Recording, 1)]
    public partial class NuevoLitigio : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::SuraClaims.SuraClaimsRepository repository.
        /// </summary>
        public static global::SuraClaims.SuraClaimsRepository repo = global::SuraClaims.SuraClaimsRepository.Instance;

        static NuevoLitigio instance = new NuevoLitigio();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public NuevoLitigio()
        {
            FechaSiniestro = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static NuevoLitigio Instance
        {
            get { return instance; }
        }

#region Variables

        string _FechaSiniestro;

        /// <summary>
        /// Gets or sets the value of variable FechaSiniestro.
        /// </summary>
        [TestVariable("f00b6613-e214-42de-b24c-47e63f4e8909")]
        public string FechaSiniestro
        {
            get { return _FechaSiniestro; }
            set { _FechaSiniestro = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("e7903828-6ac1-46d3-a887-f52fdafb621a")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable TipoLitigio.
        /// </summary>
        [TestVariable("e783f84c-b0da-4951-8be6-9f474f4f3f92")]
        public string TipoLitigio
        {
            get { return repo.TipoLitigio; }
            set { repo.TipoLitigio = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.JuiciosYMediaciones.bttn_NuevoLitigio' at Center.", repo.SuraClaims.JuiciosYMediaciones.bttn_NuevoLitigioInfo, new RecordItemIndex(0));
            repo.SuraClaims.JuiciosYMediaciones.bttn_NuevoLitigio.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 20s to exist. Associated repository item: 'SuraClaims.JuiciosYMediaciones.txt_NuevoRegistro'", repo.SuraClaims.JuiciosYMediaciones.txt_NuevoRegistroInfo, new ActionTimeout(20000), new RecordItemIndex(1));
            repo.SuraClaims.JuiciosYMediaciones.txt_NuevoRegistroInfo.WaitForExists(20000);
            
            // Tipo de litigio
            Report.Log(ReportLevel.Info, "Section", "Tipo de litigio", new RecordItemIndex(2));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.JuiciosYMediaciones.input_TipoLitigio' at Center.", repo.SuraClaims.JuiciosYMediaciones.input_TipoLitigioInfo, new RecordItemIndex(3));
            repo.SuraClaims.JuiciosYMediaciones.input_TipoLitigio.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.JuiciosYMediaciones.option_Litigio' at Center.", repo.SuraClaims.JuiciosYMediaciones.option_LitigioInfo, new RecordItemIndex(4));
            repo.SuraClaims.JuiciosYMediaciones.option_Litigio.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'SuraClaims.JuiciosYMediaciones.Copy_of_input_TipoLitigio'", repo.SuraClaims.JuiciosYMediaciones.Copy_of_input_TipoLitigioInfo, new ActionTimeout(30000), new RecordItemIndex(5));
            repo.SuraClaims.JuiciosYMediaciones.Copy_of_input_TipoLitigioInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Litigio2' with focus on 'SuraClaims.JuiciosYMediaciones.input_Caratula'.", repo.SuraClaims.JuiciosYMediaciones.input_CaratulaInfo, new RecordItemIndex(6));
            repo.SuraClaims.JuiciosYMediaciones.input_Caratula.PressKeys("Litigio2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.JuiciosYMediaciones.txt_NuevoRegistro' at Center.", repo.SuraClaims.JuiciosYMediaciones.txt_NuevoRegistroInfo, new RecordItemIndex(7));
            repo.SuraClaims.JuiciosYMediaciones.txt_NuevoRegistro.Click();
            Delay.Milliseconds(0);
            
            // Fecha notificación de demanda y audiencia
            Report.Log(ReportLevel.Info, "Section", "Fecha notificación de demanda y audiencia", new RecordItemIndex(8));
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'SuraClaims.JuiciosYMediaciones.txt_FechaSiniestro' and assigning its value to variable 'FechaSiniestro'.", repo.SuraClaims.JuiciosYMediaciones.txt_FechaSiniestroInfo, new RecordItemIndex(9));
            FechaSiniestro = repo.SuraClaims.JuiciosYMediaciones.txt_FechaSiniestro.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$FechaSiniestro' with focus on 'SuraClaims.JuiciosYMediaciones.input_FechaNotificacionDemanda'.", repo.SuraClaims.JuiciosYMediaciones.input_FechaNotificacionDemandaInfo, new RecordItemIndex(10));
            repo.SuraClaims.JuiciosYMediaciones.input_FechaNotificacionDemanda.PressKeys(FechaSiniestro);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.JuiciosYMediaciones.txt_NuevoRegistro' at Center.", repo.SuraClaims.JuiciosYMediaciones.txt_NuevoRegistroInfo, new RecordItemIndex(11));
            repo.SuraClaims.JuiciosYMediaciones.txt_NuevoRegistro.Click();
            Delay.Milliseconds(0);
            
            // Notificación
            Report.Log(ReportLevel.Info, "Section", "Notificación", new RecordItemIndex(12));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.JuiciosYMediaciones.rdbutton_NotificacionSura' at Center.", repo.SuraClaims.JuiciosYMediaciones.rdbutton_NotificacionSuraInfo, new RecordItemIndex(13));
            repo.SuraClaims.JuiciosYMediaciones.rdbutton_NotificacionSura.Click();
            Delay.Milliseconds(0);
            
            // Reserva
            Report.Log(ReportLevel.Info, "Section", "Reserva", new RecordItemIndex(14));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '8500' with focus on 'SuraClaims.JuiciosYMediaciones.input_Reserva'.", repo.SuraClaims.JuiciosYMediaciones.input_ReservaInfo, new RecordItemIndex(15));
            repo.SuraClaims.JuiciosYMediaciones.input_Reserva.PressKeys("8500");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.JuiciosYMediaciones.txt_NuevoRegistro' at Center.", repo.SuraClaims.JuiciosYMediaciones.txt_NuevoRegistroInfo, new RecordItemIndex(16));
            repo.SuraClaims.JuiciosYMediaciones.txt_NuevoRegistro.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
