///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SuraClaims.Administracion
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ReaunudarProcesos recording.
    /// </summary>
    [TestModule("33f90de9-2d4e-499e-b35d-49aa3c911607", ModuleType.Recording, 1)]
    public partial class ReaunudarProcesos : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::SuraClaims.SuraClaimsRepository repository.
        /// </summary>
        public static global::SuraClaims.SuraClaimsRepository repo = global::SuraClaims.SuraClaimsRepository.Instance;

        static ReaunudarProcesos instance = new ReaunudarProcesos();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ReaunudarProcesos()
        {
            servicioSuspendido = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ReaunudarProcesos Instance
        {
            get { return instance; }
        }

#region Variables

        string _servicioSuspendido;

        /// <summary>
        /// Gets or sets the value of variable servicioSuspendido.
        /// </summary>
        [TestVariable("a4ff4568-ceae-431b-92ca-d16e8b4ba517")]
        public string servicioSuspendido
        {
            get { return _servicioSuspendido; }
            set { _servicioSuspendido = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("e7903828-6ac1-46d3-a887-f52fdafb621a")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Administracion.check_ServicioSuspendido' at Center.", repo.SuraClaims.Administracion.check_ServicioSuspendidoInfo, new RecordItemIndex(0));
            repo.SuraClaims.Administracion.check_ServicioSuspendido.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'SuraClaims.Administracion.nombreServicioSuspendido' and assigning its value to variable 'servicioSuspendido'.", repo.SuraClaims.Administracion.nombreServicioSuspendidoInfo, new RecordItemIndex(1));
            servicioSuspendido = repo.SuraClaims.Administracion.nombreServicioSuspendido.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", "Se está reanudando el servicio:", new RecordItemIndex(2));
            
            Report.Log(ReportLevel.Info, "User", servicioSuspendido, new RecordItemIndex(3));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Administracion.bttn_Reanudar' at Center.", repo.SuraClaims.Administracion.bttn_ReanudarInfo, new RecordItemIndex(4));
            repo.SuraClaims.Administracion.bttn_Reanudar.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(5));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{F5}' with focus on 'SuraClaims'.", repo.SuraClaims.SelfInfo, new RecordItemIndex(6));
            repo.SuraClaims.Self.EnsureVisible();
            Keyboard.Press("{F5}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to exist. Associated repository item: 'SuraClaims.Administracion.txt_ColasDeMensajes'", repo.SuraClaims.Administracion.txt_ColasDeMensajesInfo, new ActionTimeout(10000), new RecordItemIndex(7));
            repo.SuraClaims.Administracion.txt_ColasDeMensajesInfo.WaitForExists(10000);
            
            existeOtroSuspendido();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
