///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SuraClaims
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DatosFastTrack recording.
    /// </summary>
    [TestModule("9228f25c-a0ec-42cb-9b29-98a2e51b62e6", ModuleType.Recording, 1)]
    public partial class DatosFastTrack : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SuraClaimsRepository repository.
        /// </summary>
        public static SuraClaimsRepository repo = SuraClaimsRepository.Instance;

        static DatosFastTrack instance = new DatosFastTrack();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DatosFastTrack()
        {
            Descripcion = "Cerradura";
            Gravedad = "Pérdidas parciales";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DatosFastTrack Instance
        {
            get { return instance; }
        }

#region Variables

        string _Descripcion;

        /// <summary>
        /// Gets or sets the value of variable Descripcion.
        /// </summary>
        [TestVariable("f6d32a4a-85e4-4725-a2b9-53f2d0712ed0")]
        public string Descripcion
        {
            get { return _Descripcion; }
            set { _Descripcion = value; }
        }

        string _Gravedad;

        /// <summary>
        /// Gets or sets the value of variable Gravedad.
        /// </summary>
        [TestVariable("e6e0cdbd-318b-4536-b18f-cde1d4600023")]
        public string Gravedad
        {
            get { return _Gravedad; }
            set { _Gravedad = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("e7903828-6ac1-46d3-a887-f52fdafb621a")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable DANIOS.
        /// </summary>
        [TestVariable("73b293f5-81d3-4f77-9d30-008f1b362d6d")]
        public string DANIOS
        {
            get { return repo.DANIOS; }
            set { repo.DANIOS = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.tag_Vehiculo' at 21;8.", repo.SuraClaims.Motor.InformacionSiniestro.tag_VehiculoInfo, new RecordItemIndex(0));
            repo.SuraClaims.Motor.InformacionSiniestro.tag_Vehiculo.Click("21;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoAsegurado'", repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoAseguradoInfo, new ActionTimeout(30000), new RecordItemIndex(1));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoAseguradoInfo.WaitForExists(30000);
            
            // Datos de conductor y acompañante
            Report.Log(ReportLevel.Info, "Section", "Datos de conductor y acompañante", new RecordItemIndex(2));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.bttn_AgregarConductor' at 46;4.", repo.SuraClaims.Motor.InformacionSiniestro.bttn_AgregarConductorInfo, new RecordItemIndex(3));
            repo.SuraClaims.Motor.InformacionSiniestro.bttn_AgregarConductor.Click("46;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SuraClaims.Motor.InformacionSiniestro.txt_DetalleDeLosLesionados'", repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDeLosLesionadosInfo, new ActionTimeout(30000), new RecordItemIndex(4));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDeLosLesionadosInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.picker_Personal' at Center.", repo.SuraClaims.Motor.InformacionSiniestro.picker_PersonalInfo, new RecordItemIndex(5));
            repo.SuraClaims.Motor.InformacionSiniestro.picker_Personal.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.option_Nombre2' at 35;12.", repo.SuraClaims.Motor.option_Nombre2Info, new RecordItemIndex(6));
            repo.SuraClaims.Motor.option_Nombre2.Click("35;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SuraClaims.Motor.InformacionSiniestro.txt_RelacionConPropietario_Asegurado'", repo.SuraClaims.Motor.InformacionSiniestro.txt_RelacionConPropietario_AseguradoInfo, new ActionTimeout(30000), new RecordItemIndex(7));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_RelacionConPropietario_AseguradoInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.bttn_Aceptar' at 22;3.", repo.SuraClaims.Motor.InformacionSiniestro.bttn_AceptarInfo, new RecordItemIndex(8));
            repo.SuraClaims.Motor.InformacionSiniestro.bttn_Aceptar.Click("22;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoAsegurado'", repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoAseguradoInfo, new ActionTimeout(30000), new RecordItemIndex(9));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoAseguradoInfo.WaitForExists(30000);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.SuraClaims.Self, false, new RecordItemIndex(10));
            
            // Descripción del tipo de siniestro
            Report.Log(ReportLevel.Info, "Section", "Descripción del tipo de siniestro", new RecordItemIndex(11));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.lbl_DescripcionTipoSiniestro' at Center.", repo.SuraClaims.Motor.InformacionSiniestro.lbl_DescripcionTipoSiniestroInfo, new RecordItemIndex(12));
            repo.SuraClaims.Motor.InformacionSiniestro.lbl_DescripcionTipoSiniestro.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SuraClaims.Motor.InformacionSiniestro.txt_Danios'", repo.SuraClaims.Motor.InformacionSiniestro.txt_DaniosInfo, new ActionTimeout(30000), new RecordItemIndex(13));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_DaniosInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.cb_Danios' at Center.", repo.SuraClaims.Motor.InformacionSiniestro.cb_DaniosInfo, new RecordItemIndex(14));
            repo.SuraClaims.Motor.InformacionSiniestro.cb_Danios.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SuraClaims.Motor.InformacionSiniestro.txt_Gravedad'", repo.SuraClaims.Motor.InformacionSiniestro.txt_GravedadInfo, new ActionTimeout(30000), new RecordItemIndex(15));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_GravedadInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'SuraClaims.Motor.InformacionSiniestro.txtbox_Gravedad'.", repo.SuraClaims.Motor.InformacionSiniestro.txtbox_GravedadInfo, new RecordItemIndex(16));
            Keyboard.PrepareFocus(repo.SuraClaims.Motor.InformacionSiniestro.txtbox_Gravedad);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Gravedad' with focus on 'SuraClaims.Motor.InformacionSiniestro.txtbox_Gravedad'.", repo.SuraClaims.Motor.InformacionSiniestro.txtbox_GravedadInfo, new RecordItemIndex(17));
            repo.SuraClaims.Motor.InformacionSiniestro.txtbox_Gravedad.PressKeys(Gravedad);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoAsegurado' at Center.", repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoAseguradoInfo, new RecordItemIndex(18));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoAsegurado.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionBasica.option_Nombre' at 26;9.", repo.SuraClaims.Motor.InformacionBasica.option_NombreInfo, new RecordItemIndex(19));
            //repo.SuraClaims.Motor.InformacionBasica.option_Nombre.Click("26;9");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SuraClaims.Motor.InformacionSiniestro.bttn_Agregar'", repo.SuraClaims.Motor.InformacionSiniestro.bttn_AgregarInfo, new ActionTimeout(30000), new RecordItemIndex(20));
            repo.SuraClaims.Motor.InformacionSiniestro.bttn_AgregarInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.bttn_Agregar' at 18;6.", repo.SuraClaims.Motor.InformacionSiniestro.bttn_AgregarInfo, new RecordItemIndex(21));
            repo.SuraClaims.Motor.InformacionSiniestro.bttn_Agregar.Click("18;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.tag_Descripcion' at 35;11.", repo.SuraClaims.Motor.InformacionSiniestro.tag_DescripcionInfo, new RecordItemIndex(22));
            repo.SuraClaims.Motor.InformacionSiniestro.tag_Descripcion.Click("35;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'SuraClaims.Motor.InformacionSiniestro.tag_Descripcion'.", repo.SuraClaims.Motor.InformacionSiniestro.tag_DescripcionInfo, new RecordItemIndex(23));
            Keyboard.PrepareFocus(repo.SuraClaims.Motor.InformacionSiniestro.tag_Descripcion);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Descripcion' with focus on 'SuraClaims.Motor.InformacionSiniestro.tag_Descripcion'.", repo.SuraClaims.Motor.InformacionSiniestro.tag_DescripcionInfo, new RecordItemIndex(24));
            repo.SuraClaims.Motor.InformacionSiniestro.tag_Descripcion.PressKeys(Descripcion);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoAsegurado' at Center.", repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoAseguradoInfo, new RecordItemIndex(25));
            repo.SuraClaims.Motor.InformacionSiniestro.txt_DetalleDelVehiculoAsegurado.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(26));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
