///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SuraClaims
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InformacionSiniestro_Motor_UBER recording.
    /// </summary>
    [TestModule("335b1193-4ca1-4305-99be-324813a08a34", ModuleType.Recording, 1)]
    public partial class InformacionSiniestro_Motor_UBER : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SuraClaimsRepository repository.
        /// </summary>
        public static SuraClaimsRepository repo = SuraClaimsRepository.Instance;

        static InformacionSiniestro_Motor_UBER instance = new InformacionSiniestro_Motor_UBER();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InformacionSiniestro_Motor_UBER()
        {
            DetalleSiniestro = "Ingreso el detalle del siniestro ocurrido";
            CausaSiniestro = "Otros";
            TipoCalle = "Calle";
            Provincia = "BUENOS AIRES";
            Localidad = "LOMAS DE ZAMORA";
            Calle = "Loria";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InformacionSiniestro_Motor_UBER Instance
        {
            get { return instance; }
        }

#region Variables

        string _DetalleSiniestro;

        /// <summary>
        /// Gets or sets the value of variable DetalleSiniestro.
        /// </summary>
        [TestVariable("e900df8d-a096-4f12-b5b9-7f7165ecf96d")]
        public string DetalleSiniestro
        {
            get { return _DetalleSiniestro; }
            set { _DetalleSiniestro = value; }
        }

        string _CausaSiniestro;

        /// <summary>
        /// Gets or sets the value of variable CausaSiniestro.
        /// </summary>
        [TestVariable("32648fde-a792-4bd2-8843-ab929cd86b7d")]
        public string CausaSiniestro
        {
            get { return _CausaSiniestro; }
            set { _CausaSiniestro = value; }
        }

        string _TipoCalle;

        /// <summary>
        /// Gets or sets the value of variable TipoCalle.
        /// </summary>
        [TestVariable("7d8a40b4-cb6d-4f97-bb10-82161197436a")]
        public string TipoCalle
        {
            get { return _TipoCalle; }
            set { _TipoCalle = value; }
        }

        string _Provincia;

        /// <summary>
        /// Gets or sets the value of variable Provincia.
        /// </summary>
        [TestVariable("635f31ac-9079-4677-a7b3-388a3ded1533")]
        public string Provincia
        {
            get { return _Provincia; }
            set { _Provincia = value; }
        }

        string _Localidad;

        /// <summary>
        /// Gets or sets the value of variable Localidad.
        /// </summary>
        [TestVariable("3a1cd2bf-dfea-4767-9a0f-6a4c889cce4a")]
        public string Localidad
        {
            get { return _Localidad; }
            set { _Localidad = value; }
        }

        string _Calle;

        /// <summary>
        /// Gets or sets the value of variable Calle.
        /// </summary>
        [TestVariable("aced0f7b-18bd-449c-8404-19d7faef06e9")]
        public string Calle
        {
            get { return _Calle; }
            set { _Calle = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("e7903828-6ac1-46d3-a887-f52fdafb621a")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Datos UBER
            Report.Log(ReportLevel.Info, "Section", "Datos UBER", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.AP_Uber.txt_SAFE' at Center.", repo.SuraClaims.AP_Uber.txt_SAFEInfo, new RecordItemIndex(1));
            repo.SuraClaims.AP_Uber.txt_SAFE.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}' with focus on 'SuraClaims.AP_Uber.txt_SAFE'.", repo.SuraClaims.AP_Uber.txt_SAFEInfo, new RecordItemIndex(2));
            repo.SuraClaims.AP_Uber.txt_SAFE.PressKeys("{LControlKey down}{Akey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1627373' with focus on 'SuraClaims.AP_Uber.txt_SAFE'.", repo.SuraClaims.AP_Uber.txt_SAFEInfo, new RecordItemIndex(3));
            repo.SuraClaims.AP_Uber.txt_SAFE.PressKeys("1627373");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Txt_Validaciones.txt_Paso3' at Center.", repo.SuraClaims.Txt_Validaciones.txt_Paso3Info, new RecordItemIndex(4));
            repo.SuraClaims.Txt_Validaciones.txt_Paso3.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'SuraClaims.AP_Uber.Copy_of_txt_SAFE'", repo.SuraClaims.AP_Uber.Copy_of_txt_SAFEInfo, new ActionTimeout(30000), new RecordItemIndex(5));
            repo.SuraClaims.AP_Uber.Copy_of_txt_SAFEInfo.WaitForNotExists(30000);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.SuraClaims.Self, false, new RecordItemIndex(6));
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.txtNivel' at 7;13.", repo.SuraClaims.Motor.InformacionSiniestro.txtNivelInfo, new RecordItemIndex(7));
            //repo.SuraClaims.Motor.InformacionSiniestro.txtNivel.Click("7;13");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.InformacionPagoSiniestro.option_NombreMayusculas' at 17;13.", repo.SuraClaims.InformacionPagoSiniestro.option_NombreMayusculasInfo, new RecordItemIndex(8));
            //repo.SuraClaims.InformacionPagoSiniestro.option_NombreMayusculas.Click("17;13");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.txtEstado' at 6;10.", repo.SuraClaims.Motor.InformacionSiniestro.txtEstadoInfo, new RecordItemIndex(9));
            //repo.SuraClaims.Motor.InformacionSiniestro.txtEstado.Click("6;10");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.InformacionPagoSiniestro.option_NombreMayusculas' at 34;9.", repo.SuraClaims.InformacionPagoSiniestro.option_NombreMayusculasInfo, new RecordItemIndex(10));
            //repo.SuraClaims.InformacionPagoSiniestro.option_NombreMayusculas.Click("34;9");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SuraClaims.Motor.InformacionSiniestro.txt_DatosUber' at Center.", repo.SuraClaims.Motor.InformacionSiniestro.txt_DatosUberInfo, new RecordItemIndex(11));
            //repo.SuraClaims.Motor.InformacionSiniestro.txt_DatosUber.Click();
            //Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
